[project]
name = "starfall-sdk"
version = "0.1.1"
description = "StarFall Partners API SDK"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "pydantic>=2.11.7",
]
